/*
 * This file is generated by jOOQ.
*/
package com.the9o.demo.jooq.models;


import com.the9o.demo.jooq.models.tables.Customer;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.customer</code>.
     */
    public static final Customer CUSTOMER = com.the9o.demo.jooq.models.tables.Customer.CUSTOMER;
}
